### PR TITLE
Add WiFi selector to captive page in initial setup

### PR DESCRIPTION
**Pull request by jandegraaf**
Plus some JS, HTML and CSS rework.

Added some text and changed some other on the "saved_html"page.

Fixed a typo in my last PR.

### CODE REVIEW

**Comment by AWSW-de** [comment]
Hi, 
thanks a lot. Just had a quick look. Compiling and updateing an existing device was no problem.
After the "Reset WiFi" button was used i tried to see the new pages, which the first 2 look already better! =)

When you get to the page where the button now is "Scanning WiFis..." the ESP32 D1 mini reboots with this output in the serial monitor:

`WordClock Captive Portal web server started
Scan WiFi networks - START
E (102628) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (102628) task_wdt:  - async_tcp (CPU 0/1)
E (102628) task_wdt: Tasks currently running:
E (102628) task_wdt: CPU 0: IDLE
E (102628) task_wdt: CPU 1: loopTask
E (102628) task_wdt: Aborting.
abort() was called at PC 0x400fd3f4 on core 0
Backtrace: 0x40083d5d:0x3ffbed3c |<-CORRUPTED
ELF file SHA256: 4488df33cd403492
Rebooting...`

Any ideas to that? Did this work with your device? 

Thanks and kind regards :)

**Comment by jandegraaf** [comment]
Hi,

Yes, I had this issue at the start, but with some tinkering in the code, I got it to disappear. 

It could be that it is triggered depending on the amount of WiFis around the ESP.

I can look into it and refactor ScanWifi() to generate the HTML for the WiFi selector.

Regards 8)

**Comment by jandegraaf** [comment]
Merged v3.2.0 and refactored ScanWifi() 

Was CaptivePotalSetup() mispelled on purpose?

**Comment by jandegraaf** [comment]
> Hi Jan, thanks I will give it a try with your build. Thanks for solving the merge problems. =)

no problem, hope I didn't loose a line 8)

**Comment by AWSW-de** [comment]
> Merged v3.2.0 and refactored ScanWifi()
> 
> Was CaptivePotalSetup() mispelled on purpose?

I think it was just to late at that time ;) Thanks

**Comment by AWSW-de** [comment]
That looks really nice and well working in the first about 15 tests on PC, iPad and iPhone... Well done :) I will test this some more and then i think you added a great new function. Thanks a lot! Have a nice weekend :)

**Comment by AWSW-de** [comment]
Merge done. Thanks a lot for this! :)

**Pull request merged**
